WATER_LABEL = 4
WATER_NEAR_LAND_LABEL = 3
DARK_WATER_LABEL = 5
WATER_NEAR_LAND_LOW_COH_LABEL = 6
WATER_LOW_COH_LABEL = 7

WATER_LABELS = [WATER_LABEL,
                WATER_NEAR_LAND_LABEL,
                DARK_WATER_LABEL,
                WATER_NEAR_LAND_LOW_COH_LABEL,
                WATER_LOW_COH_LABEL]
